"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.maxYieldMs = exports.continuousYieldMs = exports.frameYieldMs = exports.enableIsInputPendingContinuous = exports.enableProfiling = exports.enableIsInputPending = exports.enableSchedulerDebugging = void 0;
exports.enableSchedulerDebugging = false;
exports.enableIsInputPending = false;
exports.enableProfiling = false;
exports.enableIsInputPendingContinuous = false;
exports.frameYieldMs = 5;
exports.continuousYieldMs = 50;
exports.maxYieldMs = 300;
