"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.version = exports.preinitModule = exports.preinit = exports.preloadModule = exports.preload = exports.preconnect = exports.prefetchDNS = exports.useFormState = exports.useFormStatus = exports.unstable_renderSubtreeIntoContainer = exports.unstable_batchedUpdates = exports.unmountComponentAtNode = exports.render = exports.hydrate = exports.flushSync = exports.findDOMNode = exports.hydrateRoot = exports.createRoot = exports.createPortal = exports.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = void 0;
var ReactDOMSharedInternals_1 = require("@z-react-dom/ReactDOMSharedInternals");
Object.defineProperty(exports, "__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED", { enumerable: true, get: function () { return ReactDOMSharedInternals_1.default; } });
var ReactDOM_1 = require("@z-react-dom/client/ReactDOM");
Object.defineProperty(exports, "createPortal", { enumerable: true, get: function () { return ReactDOM_1.createPortal; } });
Object.defineProperty(exports, "createRoot", { enumerable: true, get: function () { return ReactDOM_1.createRoot; } });
Object.defineProperty(exports, "hydrateRoot", { enumerable: true, get: function () { return ReactDOM_1.hydrateRoot; } });
Object.defineProperty(exports, "findDOMNode", { enumerable: true, get: function () { return ReactDOM_1.findDOMNode; } });
Object.defineProperty(exports, "flushSync", { enumerable: true, get: function () { return ReactDOM_1.flushSync; } });
Object.defineProperty(exports, "hydrate", { enumerable: true, get: function () { return ReactDOM_1.hydrate; } });
Object.defineProperty(exports, "render", { enumerable: true, get: function () { return ReactDOM_1.render; } });
Object.defineProperty(exports, "unmountComponentAtNode", { enumerable: true, get: function () { return ReactDOM_1.unmountComponentAtNode; } });
Object.defineProperty(exports, "unstable_batchedUpdates", { enumerable: true, get: function () { return ReactDOM_1.unstable_batchedUpdates; } });
Object.defineProperty(exports, "unstable_renderSubtreeIntoContainer", { enumerable: true, get: function () { return ReactDOM_1.unstable_renderSubtreeIntoContainer; } });
Object.defineProperty(exports, "useFormStatus", { enumerable: true, get: function () { return ReactDOM_1.useFormStatus; } });
Object.defineProperty(exports, "useFormState", { enumerable: true, get: function () { return ReactDOM_1.useFormState; } });
Object.defineProperty(exports, "prefetchDNS", { enumerable: true, get: function () { return ReactDOM_1.prefetchDNS; } });
Object.defineProperty(exports, "preconnect", { enumerable: true, get: function () { return ReactDOM_1.preconnect; } });
Object.defineProperty(exports, "preload", { enumerable: true, get: function () { return ReactDOM_1.preload; } });
Object.defineProperty(exports, "preloadModule", { enumerable: true, get: function () { return ReactDOM_1.preloadModule; } });
Object.defineProperty(exports, "preinit", { enumerable: true, get: function () { return ReactDOM_1.preinit; } });
Object.defineProperty(exports, "preinitModule", { enumerable: true, get: function () { return ReactDOM_1.preinitModule; } });
Object.defineProperty(exports, "version", { enumerable: true, get: function () { return ReactDOM_1.version; } });
